<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Michelle Mendez &amp; Rick O. Gilmore" />


<title>walk-sleep</title>

<script src="walk-sleep_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="walk-sleep_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="walk-sleep_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="walk-sleep_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="walk-sleep_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="walk-sleep_files/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="walk-sleep_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="walk-sleep_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="walk-sleep_files/navigation-1.1/tabsets.js"></script>
<script src="walk-sleep_files/navigation-1.1/codefolding.js"></script>
<link href="walk-sleep_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="walk-sleep_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>



<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">walk-sleep</h1>
<h4 class="author">Michelle Mendez &amp; Rick O. Gilmore</h4>
<h4 class="date">2019-04-04 12:44:53</h4>

</div>


<div id="purpose" class="section level1">
<h1><span class="header-section-number">1</span> Purpose</h1>
<p>Using the PLAY project pilot data, compare a child’s sleeping patterns with the age they began crawling and walking and their method of childcare.</p>
<p>To see if there is a correlation between number of hours of sleep a child gets at night, their method of childcare and the amount of time they went from crawling to walking</p>
</div>
<div id="gather" class="section level1">
<h1><span class="header-section-number">2</span> Gather</h1>
<p>Import data from a csv file stored in <code>walk-sleep_data/</code>.</p>
<pre class="r"><code>data_dir &lt;- &#39;walk-sleep_data/&#39;
walk_sleep &lt;- read_csv(&#39;walk-sleep_data/walk-sleep.csv&#39;)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   ID = col_double(),
##   crawl_mos = col_character(),
##   walk_mos = col_double(),
##   X = col_double(),
##   to_sleep = col_time(format = &quot;&quot;),
##   awake = col_time(format = &quot;&quot;),
##   sleep_hrs = col_time(format = &quot;&quot;),
##   childcare = col_character()
## )</code></pre>
</div>
<div id="clean" class="section level1">
<h1><span class="header-section-number">3</span> Clean</h1>
<p>We need to make sure that <code>crawl_mos</code>, and <code>sleep_hrs</code> are numbers.</p>
<pre class="r"><code>walk_sleep$crawl_mos &lt;- as.numeric(walk_sleep$crawl_mos)</code></pre>
<pre><code>## Warning: NAs introduced by coercion</code></pre>
<pre class="r"><code>walk_sleep$sleep_hrs &lt;- lubridate::hms(walk_sleep$sleep_hrs)</code></pre>
</div>
<div id="visualize" class="section level1">
<h1><span class="header-section-number">4</span> Visualize</h1>
<p>We will define some common graph theme elements here.</p>
<pre class="r"><code>my_theme &lt;- theme(axis.text.x = element_text(size = rel(1.5)),
                  axis.text.y = element_text(size = rel(1.5)),
                  plot.title = element_text(size = rel(3)),
                  axis.title = element_text(size = rel(2)),
                  legend.text = element_text(size = rel(2))) +
  theme_classic()</code></pre>
<p>Hours of night sleep by age at walk onset.</p>
<pre class="r"><code>walk_sleep %&gt;%
  ggplot() +
  aes(x = walk_mos, y = as.numeric(sleep_hrs, &quot;hours&quot;)) +
  geom_point() +
  geom_smooth(method=&#39;lm&#39;, formula = y ~ x) +
  xlab(&#39;Walking onset (mos)&#39;) +
  ylab(&#39;Night sleep (hrs)&#39;) +
  my_theme</code></pre>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="walk-sleep_files/figure-html/walk-onset-sleep-hrs-1.png" width="672" /></p>
<p>Let’s also look at the total time spent crawling as a predictor. We’ll define a new variable, <code>mos_crawling</code> to do this.</p>
<pre class="r"><code>walk_sleep &lt;- walk_sleep %&gt;%
  mutate(mos_crawling = walk_mos - crawl_mos)
walk_sleep</code></pre>
<pre><code>## # A tibble: 17 x 9
##       ID crawl_mos walk_mos     X to_sleep awake sleep_hrs  childcare
##    &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;time&gt;   &lt;tim&gt; &lt;S4: Peri&gt; &lt;chr&gt;    
##  1     2      7.53    11.3   3.75 20:30    07:00 10H 30M 0S Person   
##  2     3      7.03    11.0   4.02 20:45    07:20 10H 35M 0S Center   
##  3     5      8.48    11.6   3.09 19:30    06:30 11H 0M 0S  Both     
##  4     6     12.6     16.6   3.98 19:45    07:15 11H 30M 0S Center   
##  5     7      7.2     11.7   4.47 20:30    07:00 10H 30M 0S None     
##  6     9      8.1     13     4.9  16:00    06:45 14H 45M 0S Person   
##  7    10      8       11.2   3.18 18:15    05:30 11H 15M 0S Both     
##  8    11     NA       12.1  NA    18:45    05:00 10H 15M 0S Person   
##  9    12      7.46    12.5   5.03 19:20    06:00 10H 40M 0S Center   
## 10    13      7.76    11.1   3.38 19:00    05:45 10H 45M 0S Person   
## 11    14     NA       12.2  NA    19:00    07:00 12H 0M 0S  Person   
## 12    15      7.13    11.2   4.11 20:00    06:00 10H 0M 0S  Person   
## 13    16      5.03    10.2   5.19 19:30    06:00 10H 30M 0S None     
## 14    17      5.98     9.96  3.98 20:30    07:30 11H 0M 0S  Person   
## 15    18      8.68    14     5.32 18:45    05:30 10H 45M 0S Center   
## 16    19      6.97    12.2   5.23 19:30    06:15 10H 45M 0S Person   
## 17    20      8.97    NA    NA    19:20    03:00 7H 40M 0S  Person   
## # … with 1 more variable: mos_crawling &lt;dbl&gt;</code></pre>
<p>We don’t have data for all participants here, so the sample is smaller.</p>
<pre class="r"><code>walk_sleep %&gt;%
  ggplot() +
  aes(x = mos_crawling, y = as.numeric(sleep_hrs, &quot;hours&quot;)) +
  geom_point() +
  geom_smooth(method=&#39;lm&#39;, formula = y ~ x) +
  xlab(&#39;Months spent crawling&#39;) +
  ylab(&#39;Night sleep (hrs)&#39;) +
  my_theme</code></pre>
<pre><code>## Warning: Removed 3 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 3 rows containing missing values (geom_point).</code></pre>
<p><img src="walk-sleep_files/figure-html/mos-crawling-sleep-hrs-1.png" width="672" /></p>
<pre class="r"><code>walk_sleep %&gt;%
  ggplot() +
  aes(x = as.numeric(sleep_hrs, &quot;hours&quot;), fill = childcare) +
  geom_histogram(bins = 7) +
  xlab(&#39;Night sleep (hrs)&#39;) +
  my_theme +
  theme(legend.position = &#39;bottom&#39;)</code></pre>
<p><img src="walk-sleep_files/figure-html/sleep-childcare-1.png" width="672" /></p>
</div>
<div id="analyze" class="section level1">
<h1><span class="header-section-number">5</span> Analyze</h1>
<p>We test the association between <code>sleep_hrs</code> and <code>walk_mos</code> with a Pearson’s product-moment correlation.</p>
<pre class="r"><code>c &lt;- with(walk_sleep, cor.test(as.numeric(sleep_hrs), walk_mos))
c</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  as.numeric(sleep_hrs) and walk_mos
## t = 1.2158, df = 14, p-value = 0.2441
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.2204330  0.6978418
## sample estimates:
##       cor 
## 0.3090412</code></pre>
<p>We find that there is a correlation of <span class="math inline">\(r\)</span>=0.3090412 but the 95% confidence interval of [-0.220433, 0.6978418] includes 0, so we cannot infer a relationship.</p>
<p>We also fit a linear regression line to these data. The <code>sleep_hrs</code> variable must be made numeric before we do so.</p>
<pre class="r"><code>lr &lt;- lm(formula = as.numeric(sleep_hrs) ~ walk_mos, data = walk_sleep)
summary(lr)</code></pre>
<pre><code>## 
## Call:
## lm(formula = as.numeric(sleep_hrs) ~ walk_mos, data = walk_sleep)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3188.9 -1801.2 -1087.8   455.6 12544.8 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  30463.3     7715.2   3.948  0.00146 **
## walk_mos       776.3      638.5   1.216  0.24415   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3896 on 14 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.09551,    Adjusted R-squared:  0.0309 
## F-statistic: 1.478 on 1 and 14 DF,  p-value: 0.2441</code></pre>
<p>Again, there is an expected non-zero value for the intercept, but no statistically signficant relationship between <code>sleep_hrs</code> and <code>walk_mos</code>.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
